name: amap_core_fluttify
description: An `Amap` core component, based on `fluttify` engine.
version: 0.1.0+4f403aa
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_core_fluttify

environment:
  sdk: ">=2.2.1-dev.2.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify:
    git:
      url: https://github.com/sen-Cai/foundation_fluttify.git
      ref: ebdd51b5706e05396ae716d7857eabe3c1b83ee8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_core_fluttify
    pluginClass: AmapCoreFluttifyPlugin
